version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: brokerage-firm-backend
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"